app/models.py
from flask import current_app
from app import db


class Serie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    tmdb_id = db.Column(db.Integer)
    overview = db.Column(db.Text)
    backdrop = db.Column(db.String(255))
    poster = db.Column(db.String(255))
    episodes = db.relationship("Episode", back_populates="serie", order_by="Episode.season_nr, Episode.episode_nr")


class Episode(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    serie_id = db.Column(db.Integer, db.ForeignKey('serie.id'))
    serie = db.relationship("Serie", back_populates="episodes")
    name = db.Column(db.String(255))
    season_nr = db.Column(db.Integer)
    episode_nr = db.Column(db.Integer)
    origin_name = db.Column(db.String(255))
    origin_url = db.Column(db.Text)
    tmdb_id = db.Column(db.Integer)
    overview = db.Column(db.Text)

app/__init__.py
from __future__ import unicode_literals

import logging
from logging.handlers import RotatingFileHandler
import os

from werkzeug.utils import secure_filename
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from config import Config


db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class=Config):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.serie import bp as serie_bp
    app.register_blueprint(serie_bp)

    if not app.debug and not app.testing:
        file_handler = RotatingFileHandler('/config/xstreamly.log',
                                           maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s '
            '[in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('xstreamly startup')

    return app


app = create_app()

from app import models
        

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from datetime import datetime
import os
import re
from flask import render_template, flash, redirect, url_for, request, g, jsonify, current_app
from app import db
from app.models import Serie, Episode
from app.main import bp

import youtube_dl
import tmdbsimple as tmdb

tmdb.API_KEY = os.environ.get('TMDB_API_KEY')

regex = r"^((?P<seriename>.+?)[ \._\-])?[Ss](?P<season_nr>[0-9]+)[\.\- ]?[Ee](?P<episode_nr>[0-9]+)[^\/]*$"

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    stream_url = request.form['url'] if request.method == 'POST' else request.args.get('url')

    if stream_url:
        result = {}
        ydl_opts = {'verbose': True}
        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            result = ydl.extract_info(stream_url, download=False)
            episode = save_episode(result['title'], result['webpage_url'])
        
        return render_template('main.index.html', episode=episode, history=load_history())
    return render_template('main.index.html', history=load_history())


@bp.route('/<int:episode_id>')
def play(episode_id):
    episode = Episode.query.filter_by(id=episode_id).first()
    if not episode:
        return redirect(url_for('main.index'))
    
    ydl_opts = {'verbose': True}
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        result = ydl.extract_info(episode.origin_url, download=False)
        return redirect(result['url'])


def save_episode(origin_name, origin_url):
    if not origin_name or not origin_url:
        return
    
    episode = Episode.query.filter_by(origin_url=origin_url).first()
    if episode:
        return episode

    serie = None
    matches = re.search(regex, origin_name)
    if matches and matches.group('seriename'):
        serie = save_serie(matches.group('seriename').replace('.', ' '))

    season_nr = matches.group('season_nr') if matches else None
    episode_nr = matches.group('episode_nr') if matches else None
    episode = Episode(serie=serie, season_nr=season_nr, episode_nr=episode_nr, origin_name=origin_name, origin_url=origin_url)
    db.session.add(episode)
    db.session.commit()
    return episode


def save_serie(name):
    if not name:
        return
    
    serie = Serie.query.filter_by(name=name).first()
    if serie:
        return serie
    
    response = fetch_series_from_api_by_name(name)
    tmdb_id = response['id'] if response else None
    overview = response['overview'] if response else ''
    poster = response['poster_path'] if response else ''
    backdrop = response['backdrop_path'] if response else ''

    serie = Serie(name=name, tmdb_id=tmdb_id, overview=overview, backdrop=backdrop, poster=poster)
    db.session.add(serie)
    db.session.commit()
    return serie

def fetch_series_from_api_by_name(name):
    search = tmdb.Search()
    search.tv(query=name)
    if search and len(search.results) == 1:
        return search.results[0]
    return None


def load_history():
    return Episode.query.order_by(Episode.id.desc()).all()

app/serie/__init__.py
from flask import Blueprint

bp = Blueprint('serie', __name__, url_prefix='/serie')

from app.serie import routes

app/serie/routes.py
import os

import tmdbsimple as tmdb
from app import db
from app.models import Serie
from app.serie import bp
from flask import (current_app, flash, g, jsonify, redirect, render_template,
                   request, url_for)

tmdb.API_KEY = os.environ.get('TMDB_API_KEY')


@bp.route('/', methods=['GET','POST'])
def index():
    return render_template('serie.index.html', series=Serie.query.order_by(Serie.id.desc()).all())

    
@bp.route('/<int:serie_id>', methods=['GET'])
def show(serie_id):
    serie = Serie.query.filter_by(id=serie_id).first()
    return render_template('serie.html', serie=serie)

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>XStreamly v1.0</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <link href="{{ url_for('static', filename='fontawesome/css/all.min.css') }}" rel="stylesheet" type="text/css">

    <meta name="theme-color" content="#7952b3">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet" type="text/css">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">XStreamly</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('main.index') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('serie.index') }}">Series</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container-fluid">
        <div class="row row bg-light">
            {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
            {% endfor %}

            {% block content_full %}{% endblock %}
            <div class="p-5 rounded">
            {% block content %}{% endblock %}
            </div>
        </div>
    </main>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.bundle.min.js') }}"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous">
    </script>
</body>

</html>

app/templates/main.index.html
{% extends 'base.html' %}

{% block content %}
<div class="row m-1 py-2 px-3">
    <div class="col mx-auto">
        <form action="{{ url_for('main.index') }}" method="POST"
            class="row bg-white rounded shadow-sm align-items-center justify-content-center">
            <div class="col">
                <input type="url" class="form-control border-0 bg-transparent rounded" id="urlId" name="url"
                    placeholder="URL" aria-label="URL">
            </div>
            <div class="col-auto px-0 mx-0 me-2 my-2">
                <button type="submit" class="btn btn-primary">Fetch</button>
            </div>
        </form>
    </div>
</div>

{% if history %}
<div class="row m-1 py-2 px-1">
    <div class="col mx-auto">
        <div class="list-group">
            {% for episode in history %}
            <a class="list-group-item list-group-item-action" href="{{ url_for('main.play', episode_id=episode.id) }}"
                target="_blank">
                {% if episode.serie.name|length %}
                {{ episode.serie.name }} Season {{ '%02d' % episode.season_nr }} Episode
                {{ '%02d' % episode.episode_nr }}
                {% else %}
                {{ episode.origin_name }}</h5>
                {% endif %}
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

app/templates/serie.html
{% extends 'base.html' %}

{% block content_full %}
{% if serie and serie.poster %}
<div {% if serie.backdrop %}
    style="background: linear-gradient(to right, rgb(178, 178, 178, 0.90) 150px, rgba(178, 178, 178, 0.80) 100%), url({{'https://www.themoviedb.org/t/p/w1920_and_h800_multi_faces' + serie.backdrop}}), no-repeat, fixed, center;"
    {% endif %}>
    <div class="row justify-content-md-center">
        <div class="col-2 m-2 py-2 px-1">
            <img src="https://www.themoviedb.org/t/p/w300_and_h450_bestv2{{ serie.poster }}"
                class="rounded mx-auto d-block" style="max-height: 250px;" />
        </div>
        <div class="col-8 m-1 py-5 px-1">
            <h1>{{ serie.name }}</h1>
            {{ serie.overview or '' }}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block content %}
{% if serie %}
{% if not serie.poster %}
<div class="row m-1 py-2 px-1">
    <div class="col mx-auto">
        <h1>{{ serie.name }}</h1>
    </div>
</div>
{% endif %}
{% if serie.episodes %}
<div class="row m-1 py-2 px-1">
    <div class="col mx-auto">
        <div class="list-group">
            {% for episode in serie.episodes %}
            <a class="list-group-item list-group-item-action" href="{{ url_for('main.play', episode_id=episode.id) }}"
                target="_blank">
                Season {{ '%02d' % episode.season_nr }} Episode {{ '%02d' % episode.episode_nr }}
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
{% endif %}
{% endblock %}

app/templates/serie.index.html
{% extends 'base.html' %}

{% block content %}
{% if series %}
<div class="row m-1 py-2 px-1">
    <div class="col mx-auto">
        <div class="list-group">
            {% for serie in series %}
            <a class="list-group-item list-group-item-action" href="{{ url_for('serie.show', serie_id=serie.id) }}">
                {{ serie.name }}
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}